### ISSUE TITLE
Excel report issues (Cant show pass/fail result, all is undefined)

### ISSUE THREAD

**Issue by duyphu1995** [zhengzhiqiang/cucumber-xls#1]
After run test, my code runned well, but file excel file report dont show result as i expect.
Follow some picture in this about my excel report after run test.
Please help me, only 2 days left.
![1](https://user-images.githubusercontent.com/13092483/39809098-134ca35a-53ab-11e8-8d0e-ee271ac23fd0.PNG)
![2](https://user-images.githubusercontent.com/13092483/39809099-1387f82e-53ab-11e8-8559-a43e6a25ed81.PNG)

**Comment by sowndaryayalla** [comment]
Any resolution for the above reported issue? Please help
